### ISSUE TITLE
profile['deviceMemory'] = preferences['gologin']['deviceMemory'] -> KeyError: 'gologin'

### ISSUE THREAD

**Issue by listmen001** [gologinapp/pygologin#80]
The profile was created
, the profile ID was received and specified in the code.
It gives the following error at startup:

> profile['deviceMemory'] = preferences['gologin']['deviceMemory']
KeyError: 'gologin'

Why?
There is a profile in the response to the profiles method and there is no key to it "gologin" and even more so "deviceMemory".
Then why does the gl.start() method want to find them?

**Comment by stepjet** [comment]
@listmen001 please test it with latest package version  - gologin 2024.1.22082739

**Comment by listmen001** [comment]
> @listmen001 please test it with latest package version - gologin 2024.1.22082739

I installed the library and tried to use it 2 days ago.
can't it be the last one if the version was not specified during installation?

**Comment by listmen001** [comment]
thx

**Comment by stepjet** [comment]
fixed
