### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by NuvenProjects** [gologinapp/pygologin#87]
Exception has occurred: ModuleNotFoundError
No module named 'gologin.cookiesManager'
  File "C:\Users\Administrator\Desktop\CREATE BAS FINGERPRINTS\run.py", line 6, in <module>
    from gologin import GoLogin
ModuleNotFoundError: No module named 'gologin.cookiesManager'

However:

import os
import time
import random
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from gologin import GoLogin

AND BASED ON YOUR OWN PY DOCUMENTATION, SEEMS YOU NEED TO UPDATE MAYBE, OR PASSING THE BUCK TO CLIENTS TO RESOLVE IT FOR YOU??

**Comment by stepjet** [comment]
try to install gologin via pip

**Comment by danztensai** [comment]
I have the same Problem here, did you solve it?

**Comment by bbajwa346** [comment]
I have the Same issue as well !! kindly Resolve it asap

**Comment by stepjet** [comment]
thanks for the report, please try with the latest version https://pypi.org/project/gologin/2024.5.12073431/
